/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthGithubRouteImport } from './routes/auth.github'
import { Route as AuthedWorkoutRouteImport } from './routes/_authed.workout'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth.github.callback'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubRoute = AuthGithubRouteImport.update({
  id: '/auth/github',
  path: '/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWorkoutRoute = AuthedWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthGithubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workout': typeof AuthedWorkoutRoute
  '/auth/github': typeof AuthGithubRouteWithChildren
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workout': typeof AuthedWorkoutRoute
  '/auth/github': typeof AuthGithubRouteWithChildren
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/workout': typeof AuthedWorkoutRoute
  '/auth/github': typeof AuthGithubRouteWithChildren
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workout' | '/auth/github' | '/auth/github/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workout' | '/auth/github' | '/auth/github/callback'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/workout'
    | '/auth/github'
    | '/auth/github/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthGithubRoute: typeof AuthGithubRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github': {
      id: '/auth/github'
      path: '/auth/github'
      fullPath: '/auth/github'
      preLoaderRoute: typeof AuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/workout': {
      id: '/_authed/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AuthedWorkoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof AuthGithubRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedWorkoutRoute: typeof AuthedWorkoutRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedWorkoutRoute: AuthedWorkoutRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AuthGithubRouteChildren {
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
}

const AuthGithubRouteChildren: AuthGithubRouteChildren = {
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
}

const AuthGithubRouteWithChildren = AuthGithubRoute._addFileChildren(
  AuthGithubRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthGithubRoute: AuthGithubRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
